### PR TITLE
[42] Add command line proxy for Reality entities

### PR DESCRIPTION
**Pull request by codenamev**
#42 This adds a command line tool `really` that proxies methods to `Entity`.  I can change the name of this command to something you feel is more appropriate if necessary.

As a small example (misspelling of Seinfeld is on purpose :wink:):

screen shot 2016-03-07 at 9 42 56 am

### CODE REVIEW

**Comment by zverok** [comment]
Hey, that's pretty cool!
I'm merging this and releasing with other enchancements in next version (~Mar 17). And we'll look what others say, it seems great potential here.

Thank you!

**Comment by DannyBen** [comment]
This is way beyond super cool. I saw the beginning of this discussion in #42 

As far as I see, this is not yet available in the published gem?

**Comment by smostovoy** [comment]
@DannyBen yes, it will be available in next release soon

**Comment by zverok** [comment]
Aaaaaaand finally! http://zverok.github.io/blog/2016-04-18-reality-new-release.html

@codenamev, I am really gratefull for your contribution and have added you to Contributors list in our new README

**Comment by codenamev** [comment]
Woohoo! 🎉  You da man!

**Pull request merged**
